package cat.copernic.letmedoit.General.model

import cat.copernic.letmedoit.General.model.Category
import cat.copernic.letmedoit.General.model.Subcategory

class CategoryProvider {
    companion object {
        fun obtenerCategorias(): ArrayList<Category> {
            return arrayListOf(
                Category(
                    "Informática",
                    arrayListOf(
                        Subcategory("Web", "100"),
                        Subcategory("Aplicaciones_Android", "100"),
                        Subcategory("Sistemas y_redes", "100"),
                        Subcategory("Ciberseguridad", "100"),
                        Subcategory("Videojuegos", "100"),
                        Subcategory("Aplicaciones_IOS", "100"),
                        Subcategory("Reparacion de_hardware", "100"),
                        Subcategory("Base de datos", "100"),
                        Subcategory("Inteligencia_artifical", "100"),
                        Subcategory("Robotica", "100"),
                        Subcategory("Electronica", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "email_icon",
                    "1"
                ),
                Category(
                    "Cocina",
                    arrayListOf(
                        Subcategory("Reposteria", "100"),
                        Subcategory("Cocina_Italiana", "100"),
                        Subcategory("Cocina_Mediterranea", "100"),
                        Subcategory("Bebidas_Alcoholicas", "100"),
                        Subcategory("Cocina_Francesa", "100"),
                        Subcategory("Cocina_Asiatica", "100"),
                        Subcategory("Cocina_Mejicana", "100"),
                        Subcategory("Pescaderia", "100"),
                        Subcategory("Carniceria", "100"),
                        Subcategory("Verduras", "100"),
                        Subcategory("Confiteria", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "favorites_icon",
                    "2"
                ),
                Category(
                    "Vehiculos",
                    arrayListOf(
                        Subcategory("Gasolina", "100"),
                        Subcategory("Diesel", "100"),
                        Subcategory("Mecanica", "100"),
                        Subcategory("Deportivos", "100"),
                        Subcategory("Todoterrenos", "100"),
                        Subcategory("Todocaminos", "100"),
                        Subcategory("Motocicletas", "100"),
                        Subcategory("Competiciones", "100"),
                        Subcategory("Clasicos", "100"),
                        Subcategory("Accesorios", "100"),
                        Subcategory("Alquiler", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "filter_icon",
                    "3"
                ),
                Category(
                    "Informática",
                    arrayListOf(
                        Subcategory("Web", "100"),
                        Subcategory("Aplicaciones_Android", "100"),
                        Subcategory("Sistemas y_redes", "100"),
                        Subcategory("Ciberseguridad", "100"),
                        Subcategory("Videojuegos", "100"),
                        Subcategory("Aplicaciones_IOS", "100"),
                        Subcategory("Reparacion de_hardware", "100"),
                        Subcategory("Base de datos", "100"),
                        Subcategory("Inteligencia_artifical", "100"),
                        Subcategory("Robotica", "100"),
                        Subcategory("Electronica", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "email_icon",
                    "1"
                ),
                Category(
                    "Cocina",
                    arrayListOf(
                        Subcategory("Reposteria", "100"),
                        Subcategory("Cocina_Italiana", "100"),
                        Subcategory("Cocina_Mediterranea", "100"),
                        Subcategory("Bebidas_Alcoholicas", "100"),
                        Subcategory("Cocina_Francesa", "100"),
                        Subcategory("Cocina_Asiatica", "100"),
                        Subcategory("Cocina_Mejicana", "100"),
                        Subcategory("Pescaderia", "100"),
                        Subcategory("Carniceria", "100"),
                        Subcategory("Verduras", "100"),
                        Subcategory("Confiteria", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "favorites_icon",
                    "2"
                ),
                Category(
                    "Vehiculos",
                    arrayListOf(
                        Subcategory("Gasolina", "100"),
                        Subcategory("Diesel", "100"),
                        Subcategory("Mecanica", "100"),
                        Subcategory("Deportivos", "100"),
                        Subcategory("Todoterrenos", "100"),
                        Subcategory("Todocaminos", "100"),
                        Subcategory("Motocicletas", "100"),
                        Subcategory("Competiciones", "100"),
                        Subcategory("Clasicos", "100"),
                        Subcategory("Accesorios", "100"),
                        Subcategory("Alquiler", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "filter_icon",
                    "3"
                ),
                Category(
                    "Historia",
                    arrayListOf(
                        Subcategory("Edad media", "100"),
                        Subcategory("Edad antigua", "100"),
                        Subcategory("Prehistoria", "100"),
                        Subcategory("Libros", "100"),
                        Subcategory("Museos", "100"),
                        Subcategory("Roma", "100"),
                        Subcategory("Europa", "100"),
                        Subcategory("Guerra mundial_II", "100"),
                        Subcategory("Gran guerra", "100"),
                        Subcategory("Guerras_civiles", "100"),
                        Subcategory("Revolucion_francesa", "100"),
                        Subcategory("Clases", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Mantenimiento",
                    arrayListOf(
                        Subcategory("Fontaneria", "100"),
                        Subcategory("Electricidad", "100"),
                        Subcategory("Piscinas", "100"),
                        Subcategory("Jardineria", "100"),
                        Subcategory("Pintura", "100"),
                        Subcategory("Limpieza", "100"),
                        Subcategory("Fachada", "100"),
                        Subcategory("Seguridad del hogar", "100"),
                        Subcategory("Tejados", "100"),
                        Subcategory("Reparación", "100"),
                        Subcategory("Alquiler", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "email_icon",
                    "3"
                ),
                Category(
                    "Deportes",
                    arrayListOf(
                        Subcategory("Futbol", "100"),
                        Subcategory("Tenis", "100"),
                        Subcategory("Tenis mesa", "100"),
                        Subcategory("Natacion", "100"),
                        Subcategory("Basquet", "100"),
                        Subcategory("Futbol_americano", "100"),
                        Subcategory("Atletismo", "100"),
                        Subcategory("Gimnasia", "100"),
                        Subcategory("Hockey", "100"),
                        Subcategory("Balonmano", "100"),
                        Subcategory("Artes_marciales", "100"),
                        Subcategory("Clubs", "100"),
                    ),
                    "filter_icon",
                    "3"
                ),
                Category(
                    "Musica",
                    arrayListOf(
                        Subcategory("Composición", "100"),
                        Subcategory("Instrumentos", "100"),
                        Subcategory("M.Electronica", "100"),
                        Subcategory("Heavy Meatl", "100"),
                        Subcategory("Rock", "100"),
                        Subcategory("Altavoces", "100"),
                        Subcategory("Microfonos", "100"),
                        Subcategory("Software de_sonido", "100"),
                        Subcategory("M.Latina", "100"),
                        Subcategory("Rap", "100"),
                        Subcategory("Pop", "100"),
                        Subcategory("Clases", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Reforma",
                    arrayListOf(
                        Subcategory("Fontaneria", "100"),
                        Subcategory("Electricidad", "100"),
                        Subcategory("Fachadas", "100"),
                        Subcategory("Tejados", "100"),
                        Subcategory("Suelos", "100"),
                        Subcategory("Baños", "100"),
                        Subcategory("Pintura", "100"),
                        Subcategory("Piscinas", "100"),
                        Subcategory("Derribo", "100"),
                        Subcategory("Planches", "100"),
                        Subcategory("Herramientas", "100"),
                        Subcategory("Materiales", "100"),
                    ),
                    "filter_icon",
                    "3"
                ),
                Category(
                    "Botanica",
                    arrayListOf(
                        Subcategory("Huerto", "100"),
                        Subcategory("Flores", "100"),
                        Subcategory("Fertilizantes", "100"),
                        Subcategory("Riego", "100"),
                        Subcategory("Herramientas", "100"),
                        Subcategory("Semillas", "100"),
                        Subcategory("Servicios", "100"),
                        Subcategory("Materiales", "100"),
                        Subcategory("Arboles", "100"),
                        Subcategory("Arbustos", "100"),
                        Subcategory("Plantas mutantes", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "email_icon",
                    "3"
                ),
                Category(
                    "Animales",
                    arrayListOf(
                        Subcategory("Comidad", "100"),
                        Subcategory("Accesorios", "100"),
                        Subcategory("Paseo", "100"),
                        Subcategory("Pipican", "100"),
                        Subcategory("Peluqueria", "100"),
                        Subcategory("Veterinaria", "100"),
                        Subcategory("Juguetes", "100"),
                        Subcategory("Perros", "100"),
                        Subcategory("Gatos", "100"),
                        Subcategory("Caballos", "100"),
                        Subcategory("Pajaros", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Geologia",
                    arrayListOf(
                        Subcategory("Rocas", "100"),
                        Subcategory("Minerales", "100"),
                        Subcategory("Excavacion", "100"),
                        Subcategory("Anilisis de terreno", "100"),
                        Subcategory("Volcanes", "100"),
                        Subcategory("Tasascion", "100"),
                        Subcategory("Rocas", "100"),
                        Subcategory("Minerales", "100"),
                        Subcategory("Excavacion", "100"),
                        Subcategory("Anilisis de terreno", "100"),
                        Subcategory("Volcanes", "100"),
                        Subcategory("Tasascion", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Literatura",
                    arrayListOf(
                        Subcategory("Clasica", "100"),
                        Subcategory("Romance", "100"),
                        Subcategory("Edicion", "100"),
                        Subcategory("Terror", "100"),
                        Subcategory("Comedia", "100"),
                        Subcategory("Poesia", "100"),
                        Subcategory("Misterio", "100"),
                        Subcategory("Ciencia_ficcion", "100"),
                        Subcategory("Fantasia", "100"),
                        Subcategory("San Jordi", "100"),
                        Subcategory("Juvenil", "100"),
                        Subcategory("Cervantes", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Jardineria",
                    arrayListOf(
                        Subcategory("Huerto", "100"),
                        Subcategory("Flores", "100"),
                        Subcategory("Fertilizantes", "100"),
                        Subcategory("Riego", "100"),
                        Subcategory("Herramientas", "100"),
                        Subcategory("Semillas", "100"),
                        Subcategory("Servicios", "100"),
                        Subcategory("Materiales", "100"),
                        Subcategory("Arboles", "100"),
                        Subcategory("Arbustos", "100"),
                        Subcategory("Plantas_mutantes", "100"),
                        Subcategory("Cursos", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Transporte",
                    arrayListOf(
                        Subcategory("Publico", "100"),
                        Subcategory("Taxis", "100"),
                        Subcategory("Tren", "100"),
                        Subcategory("Nacional", "100"),
                        Subcategory("Internacional", "100"),
                        Subcategory("Publico", "100"),
                        Subcategory("Taxis", "100"),
                        Subcategory("Tren", "100"),
                        Subcategory("Nacional", "100"),
                        Subcategory("Internacional", "100"),
                        Subcategory("Publico", "100"),
                        Subcategory("Taxis", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Educación",
                    arrayListOf(
                        Subcategory("Libros", "100"),
                        Subcategory("Material", "100"),
                        Subcategory("Clases", "100"),
                        Subcategory("Matematicas", "100"),
                        Subcategory("Ciencia", "100"),
                        Subcategory("Cursos", "100"),
                        Subcategory("Programas", "100"),
                        Subcategory("Instituciones", "100"),
                        Subcategory("Consejos", "100"),
                        Subcategory("Practicas", "100"),
                        Subcategory("Univeridad", "100"),
                        Subcategory("Cultura", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
                Category(
                    "Ocio",
                    arrayListOf(
                        Subcategory("Locales", "100"),
                        Subcategory("Alquiler", "100"),
                        Subcategory("Clubs", "100"),
                        Subcategory("Competiciones", "100"),
                        Subcategory("Eventos", "100"),
                        Subcategory("Hosteleria", "100"),
                        Subcategory("Turismo", "100"),
                        Subcategory("Cine", "100"),
                        Subcategory("Clubs_nocturnos", "100"),
                        Subcategory("Transporte", "100"),
                        Subcategory("Recreativos", "100"),
                        Subcategory("Formación", "100"),
                    ),
                    "favorites_icon",
                    "3"
                ),
            )
        }
    }
}