package cat.copernic.letmedoit.General.model

class UsersProvider {

    companion object{
        fun obtenerUsers() : ArrayList<Users> {
            return arrayListOf(
                Users(
                    "Pau",
                ),
                Users(
                    "IsCEDCAmael",
                ),
                Users(
                    "IsmaCDCEel",
                ),
                Users(
                    "IsWXSWmael",
                ),
                Users(
                    "IsECECmael",
                ),
                Users(
                    "Ismael",
                ),
                Users(
                    "IsCECAXSmael",
                ),
                Users(
                    "IsmCECASael",
                ),
                Users(
                    "IsmCEWCWXael",
                ),
                Users(
                    "IsmECWCWECael",
                ),
                Users(
                    "IsEECECWmael",
                ),
                Users(
                    "IsmEDEECael",
                ),
                Users(
                    "IEDEDsmael",
                ),
                Users(
                    "DEDl",
                ),
                Users(
                    "Pau",
                ),
                Users(
                    "IsCEDCAmael",
                ),
                Users(
                    "IsmaCDCEel",
                ),
                Users(
                    "IsWXSWmael",
                ),
                Users(
                    "IsECECmael",
                ),
                Users(
                    "Ismael",
                ),
                Users(
                    "IsCECAXSmael",
                ),
                Users(
                    "IsmCECASael",
                ),
                Users(
                    "IsmCEWCWXael",
                ),
                Users(
                    "IsmECWCWECael",
                ),
                Users(
                    "IsEECECWmael",
                ),
                Users(
                    "IsmEDEECael",
                ),
                Users(
                    "IEDEDsmael",
                ),
                Users(
                    "DEDl",
                ),
            )
        }
    }
}