package cat.copernic.letmedoit.Admin.model

class UsersProvider {

    companion object{
        fun obtenerUsers() : ArrayList<cat.copernic.letmedoit.Admin.model.Users> {
            return arrayListOf(
                cat.copernic.letmedoit.Admin.model.Users(
                    "Pau",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Ismael",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Lausin",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Mire",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Nico",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Maxi",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Mauri",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Jose",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Alex",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Paco",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Ares",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsmEDEECael",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IEDEDsmael",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "DEDl",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Pau",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsCEDCAmael",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsmaCDCEel",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsWXSWmael",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsECECmael",
                    true,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "Ismael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsCECAXSmael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsmCECASael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsmCEWCWXael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsmECWCWECael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsEECECWmael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IsmEDEECael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "IEDEDsmael",
                    false,
                ),
                cat.copernic.letmedoit.Admin.model.Users(
                    "DEDl",
                    false,
                ),
            )
        }
    }
}